Fix bug when only one of ref/new file has a collection
This would cause size dataframe join to fail with
ValueError: columns overlap but no suffix specified: Index([u'% (New)',
u'kb / event (New)'], dtype='object')